# Generated by Django 5.1.3 on 2024-11-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DairyManagement', '0001_initial'),
        ('accounts', '0004_milk_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters_collected', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='accounts.milk_pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milk Collection',
                'verbose_name_plural': 'Milk Collections',
            },
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
