# Generated by Django 5.1.3 on 2024-11-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_milk_pricing_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=4)),
                ('companyName', models.CharField(max_length=50)),
                ('PRN', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
