# Generated by Django 5.1.3 on 2024-11-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_purchasers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasers',
            old_name='companyName',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='purchasers',
            old_name='PRN',
            new_name='prn',
        ),
    ]
