# Generated by Django 5.1.3 on 2024-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_companyname_purchasers_companyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='milk_Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=4)),
                ('companyname', models.CharField(max_length=50)),
                ('prn', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'milk_Buyers',
                'verbose_name_plural': 'milk_Buyers',
            },
        ),
        migrations.DeleteModel(
            name='purchasers',
        ),
    ]
